/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsVestRouteImport } from './routes/projects/vest'
import { Route as ProjectsAboutRouteImport } from './routes/projects/about'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsVestRoute = ProjectsVestRouteImport.update({
  id: '/projects/vest',
  path: '/projects/vest',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsAboutRoute = ProjectsAboutRouteImport.update({
  id: '/projects/about',
  path: '/projects/about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/about': typeof ProjectsAboutRoute
  '/projects/vest': typeof ProjectsVestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/about': typeof ProjectsAboutRoute
  '/projects/vest': typeof ProjectsVestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/about': typeof ProjectsAboutRoute
  '/projects/vest': typeof ProjectsVestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects/about' | '/projects/vest'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects/about' | '/projects/vest'
  id: '__root__' | '/' | '/projects/about' | '/projects/vest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsAboutRoute: typeof ProjectsAboutRoute
  ProjectsVestRoute: typeof ProjectsVestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/vest': {
      id: '/projects/vest'
      path: '/projects/vest'
      fullPath: '/projects/vest'
      preLoaderRoute: typeof ProjectsVestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/about': {
      id: '/projects/about'
      path: '/projects/about'
      fullPath: '/projects/about'
      preLoaderRoute: typeof ProjectsAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsAboutRoute: ProjectsAboutRoute,
  ProjectsVestRoute: ProjectsVestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
